#!/bin/bash
# walker - reminds you to walk every 45 minutes

WORK_MINS=45

notify() {
    osascript -e "display notification \"$1\" with title \"Walker\" sound name \"Glass\""
}

echo "Walker started. Will remind you to walk every ${WORK_MINS} minutes."
echo "Press Ctrl+C to stop."

while true; do
    sleep $((WORK_MINS * 60))
    notify "Time to walk! Get up and move for 5 minutes."
    say "Time to walk"
done
